version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    env_file: 
      - ./frontend/.env
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: unless-stopped 
    depends_on:
      - mongo
    volumes:
      - uploads_data:/app/uploads
    environment:
      - MONGODB_URI=mongodb://mongo:27017/la-vitrina

  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=la-vitrina

volumes:
  mongo_data:
    name: la-vitrina-mongo-data
  uploads_data:
    name: la-vitrina-uploads-data
